---
- name: mariadb repository present
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: "http://yum.mariadb.org/{{ mysql_version }}/centos7-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
- name: latest mariadb packages version installed
  yum:
    name: "{{ mysql_packages }}"
    state: latest
  notify:
    - restart mariadb
  tags: update
- name: /etc/my.cnf
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  notify:
    - restart mariadb
- name: mariadb service enabled
  service:
    name: mariadb
    state: started
    enabled: yes
#- name: show
#  debug:
#    msg: "{{ item }} : {{ hostvars[item].ansible_default_ipv4.address }}"
#  with_items: "{{ groups['all'] }}"
- name: get ip addresses
  set_fact:
    client_ip_addresses: "{{ client_ip_addresses }} + [ '{{ hostvars[item].ansible_default_ipv4.address }}' ]"
  with_items: "{{ groups['all'] }}"
- name: mariadb root user password set
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  with_items:
    - "{{ client_ip_addresses }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: anonymous mariadb server user removed
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - localhost
- name: mariadb test database removed
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
- name: insert firewalld rule
  firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
...
